# Generated by Django 5.1.7 on 2025-03-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='generated_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
